name: cony springboot3 webservice 

on:
  push:
    branches: [ "master" ]

env:
  BUCKET_NAME: cony-springboot3-bucket
  DIRECTORY_NAME: cony-springboot3-directory
  CODE_DEPLOY_APP_NAME: cony-springboot3-webservice
  DEPLOYMENT_GROUP_NAME: cony-springboot3-webservice-group

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check Repo code With Submodules
        uses: actions/checkout@v3
        with:
          submodules: 'true'
          token: ${{secrets.GH_ACCESS_TOKEN}}

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2.4.2 # 버전 선택
        with:
          arguments: build

      - name: Make Zip File
        run: zip -qq -r ./$GITHUB_SHA.zip .
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://$BUCKET_NAME/$DIRECTORY_NAME/$GITHUB_SHA.zip

      - name: Deploy to EC2 Instance
        run: aws deploy create-deployment --application-name $CODE_DEPLOY_APP_NAME --deployment-group-name $DEPLOYMENT_GROUP_NAME --deployment-config-name CodeDeployDefault.OneAtATime --s3-location bucket=$BUCKET_NAME,bundleType=zip,key=$DIRECTORY_NAME/$GITHUB_SHA.zip
